import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import SimpleHeader from "@/app/shared/header/SimpleHeader";
import SimpleFooter from "./shared/footer/SimpleFooter";

const inter = localFont({ src: "../../public/fonts/Poppins-Medium.ttf" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className={`light ${inter.className}`} lang="en">
      <body className="bg-white">
        <SimpleHeader />
        {children}
        <SimpleFooter />
      </body>
    </html>
  );
}
