import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SimpleHeader from "@/app/shared/header/SimpleHeader";
import SimpleFooter from "./shared/footer/SimpleFooter";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className={`light ${inter.className}`} lang="en">
      <body className="bg-gray-50">
        <SimpleHeader />
        {children}
        <SimpleFooter />
      </body>
    </html>
  );
}
