import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SimpleHeader from "@/app/shared/header/SimpleHeader";
import SimpleFooter from "./shared/footer/SimpleFooter";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className={inter.className} lang="en">
      <SimpleHeader />
      <body>{children}</body>
      <SimpleFooter />
    </html>
  );
}
